# Generated by Django 5.1.5 on 2025-01-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryDrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.FloatField(help_text='Width of the drone')),
                ('height', models.FloatField(help_text='Height of the drone')),
                ('speed', models.FloatField(help_text='Speed of the drone')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
