# Generated by Django 5.1.5 on 2025-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='militarydrone',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the drone image', null=True),
        ),
    ]
