# Generated by Django 4.2.19 on 2025-03-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('focal_length', models.FloatField(help_text='Focal length in mm')),
                ('sensor_height', models.FloatField(help_text='Sensor height in meters')),
                ('sensor_width', models.FloatField(help_text='Sensor width in meters')),
                ('resolution', models.CharField(help_text='Resolution e.g. 1920x1080', max_length=50)),
                ('brand', models.CharField(help_text='Camera brand', max_length=255)),
            ],
        ),
    ]
